### ISSUE TITLE
Create Smart Slice Plugin with new tab to the right of "Prepare"

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#1]

**Comment by thopiekar** [comment]
Current status:
![image](https://user-images.githubusercontent.com/1847437/65455209-0e91ef00-de47-11e9-8e14-45fd13e710f9.png)

Checklist:
- [ ] "Reweighting upstream stage plugins" - https://github.com/Ultimaker/Cura/pull/6391
- [ ] Setting weight in between of prepare and preview stage
- [ ] Making final decision how to call the label

**Comment by thopiekar** [comment]
Done. The current master branch or the future 4.3 version is needed as an minimum:
![image](https://user-images.githubusercontent.com/1847437/65640527-d6c3ac80-dfea-11e9-9135-776a5f438bba.png)

**Comment by dougkenik** [comment]
Good! Can we make the title "Smart Slice" instead of "SmartSlice"?

**Comment by thopiekar** [comment]
Yes, easily! :wink:
