### ISSUE TITLE
Difficulty selecing faces after loading new model

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#100]
[Originally reported](https://trello.com/c/Wy3aSXIx/24-difficulty-selecting-faces-after-loading-new-model) by @rickdalgarno 

After running a validation, a new model is loaded into Cura. Selecting surfaces on the new model is buggy.

Steps (see attached video)
1. Load the thin dogbone and setup and run a validation. Select the surfaces as shown in the attached video.
2. Load the thick dogbone.
3. Delete the thin dogbone.
4. Enter SS stage and try to select the bottom or top surface. It is not possible. You must click a different surface 1st, then you can select the top or bottom surface.

These models are very similar. The only difference is the thickness. I suspect that the surfaces from the 1st model are not "forgotten" when the 1st model is deleted. 

This is a niche workflow. Probably not an alpha priority.

[dogbone-stls.zip](https://github.com/tetonsim/is-cura-ui/files/4346047/dogbone-stls.zip)
[video.zip](https://github.com/tetonsim/is-cura-ui/files/4346048/video.zip)

**Comment by bradymadams** [comment]
**Here's my hypothesis on the source of the bug** -- the two dogbones have identical number of triangles and the triangle ids/indices are also identical. The selected triangle index was cached from the previous model and when clicking the similar face on the new dogbone the code checked against the cached index and noticed there was no change, so it assumed no face highlighting needed to be updated.

This will likely get cleaned up and go away with the implementation of #55

**Comment by rickdalgarno** [comment]
This is fixed. Tested with Cura 4.4.1 and SmartSlicePlugin-r20.1.2.curapackage.
