### ISSUE TITLE
Issue an error message in a dialog box when face selection is not available

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#102]
We have a function in SmartSliceSelectTool that checks for face selection support, but we don't currently use it. We should use this to check if face selection is available and if not issue an error message in a dialog box.

This was a problem when trying to run Smart Slice in Cura on a virtual machine which only supported openGL 3.1. Smart Slice behaved buggy and there was no indication as to why. Having this error message would explain why Smart Slice won't work.

**Comment by colman-hartinger** [comment]
fixed error in smartSliceSelectTool.py so message would only show when user tried to select a face when not using correct version of openGL
