### ISSUE TITLE
Consume new pywim Smart Slice API

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#104]

**Comment by dougkenik** [comment]
Dependent on https://github.com/tetonsim/pywim/issues/31

**Comment by bradymadams** [comment]
This is ready pending the merge of https://github.com/tetonsim/pywim/pull/34

Additionally, here's a script and 3MF that show the basics of using the new client.

[thor-client-test.py.zip](https://github.com/tetonsim/is-cura-ui/files/4636559/thor-client-test.py.zip)
[fast-job.3mf.zip](https://github.com/tetonsim/is-cura-ui/files/4636534/fast-job.3mf.zip)
