### ISSUE TITLE
Cancel Smart Slice Job

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#11]
After a user submits a Smart Slice job (Validation or Optimization), they can cancel by selecting the "Cancel" button (shown in image below).

If the user cancels the submission, the plugin will perform the following:

- Send a cancellation request for the job ID to the AWS services
- Modify the button back to "Smart Slice" once the cancellation request has been verified

![image](https://user-images.githubusercontent.com/24813209/65929419-3c36e500-e3bf-11e9-995c-bf4e6a215957.png)

**Comment by jake-kirkland-teton** [comment]
For this, a required change will be an adjustment to how the jobs are tracked in the plugin. The current jobs tracking doesn't have the necessary ID from the new API JobInfo object, so it is unable to send that to the smartslice_job_abort function to properly abort a job. If we can attach that ID to the existing job objects that we are using now, this should be a fairly easy adjustment.
