### ISSUE TITLE
Multiple faces randomly selected

### ISSUE THREAD

**Issue by colman-hartinger** [tetonsim/is-cura-ui#121]
Using the stl file below smart slice was selecting multiple connected orthogonal faces. As seen below the two orthogonal faces inside the part are selected when the user only clicks on one of them. Alternatively the faces opposite these do not exhibit this behavior 

![bug](https://user-images.githubusercontent.com/62404177/81223826-e7d29400-8fa3-11ea-87af-bac2e8e754b4.png)

**Comment by colman-hartinger** [comment]
stl file 
[kossel_part1.zip](https://github.com/tetonsim/is-cura-ui/files/4589264/kossel_part1.zip)

**Comment by bradymadams** [comment]
There's a good chance the bug is in [pywim](https://github.com/tetonsim/pywim). If we confirm the bug is in pywim we can transfer the issue to that repo.

**Comment by colman-hartinger** [comment]
Found issue to be degenerate triangle at index 1121. Triangle has 3 co-linear vertices which is why the 2 orthogonal faces get selected

**Comment by colman-hartinger** [comment]
cura added check for degenerate meshes
![1](https://user-images.githubusercontent.com/62404177/84065792-292ed880-a982-11ea-923b-74d61c7a1b42.png)
