### ISSUE TITLE
make the load rotation manipulator

### ISSUE THREAD

**Issue by colman-hartinger** [tetonsim/is-cura-ui#143]
![image](https://user-images.githubusercontent.com/62028020/83806577-faa5ba80-a66e-11ea-9c59-6e714cff0600.png)
![image](https://user-images.githubusercontent.com/62028020/83806775-40fb1980-a66f-11ea-931c-197c97c44f41.png)
![image](https://user-images.githubusercontent.com/62028020/83806826-4fe1cc00-a66f-11ea-8ae0-c9f657af92cf.png)
![image](https://user-images.githubusercontent.com/62028020/83806865-5d975180-a66f-11ea-84df-9df9990a5b53.png)

Build tool for changing the angle of the force vectors.

**Comment by rickdalgarno** [comment]
I came across a very similar rotation manipulator in Fusion 360. Here is a screenshot of what it looks like. In addition to manually manipulating the ring, you can enter a specific angle. This isn't a requirement for us, but something to take note of.

![image](https://user-images.githubusercontent.com/34459028/83817481-1c5c6d00-a682-11ea-9bef-67c013fe0689.png)
