### ISSUE TITLE
set defaults for surface type load vector

### ISSUE THREAD

**Issue by colman-hartinger** [tetonsim/is-cura-ui#144]
Cylindrical:
![image](https://user-images.githubusercontent.com/62028020/83807542-810ecc00-a670-11ea-94b8-9ba73801055e.png)
Flat:
![image](https://user-images.githubusercontent.com/62028020/83807598-9552c900-a670-11ea-8769-4083170b0474.png)

Given flat surface or cylindrical surface set load vectors default. The default for flat surfaces should be the current normal force select tool with just an arrow, the cylindrical normal force select tool should be the rotation tool.

Dependent on Issue #143

**Comment by dougkenik** [comment]
This should be complete after #143 and #145 are done to spec

**Comment by dougkenik** [comment]
This should be changed to just defaulting to "Flat," "Normal," and not "Flipped" when a new load is created.
