### ISSUE TITLE
apply parallel transformation to load vector

### ISSUE THREAD

**Issue by colman-hartinger** [tetonsim/is-cura-ui#146]
Cylindrical:
![image](https://user-images.githubusercontent.com/62028020/83807282-0e055580-a670-11ea-9aca-b5a58d029ab1.png)
Flat:
![image](https://user-images.githubusercontent.com/62028020/83807319-1f4e6200-a670-11ea-9656-5917dfd9b90c.png)

Convert load vector to parallel loading for cylindrical and flat faces

**Comment by dougkenik** [comment]
This should be complete after #143 and #145 are done to spec
