### ISSUE TITLE
Load magnitude resets to 10 when Flip Direction is clicked

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#147]
The load magnitude resets to 10 N whenever Flip Direction is clicked.

Step to reproduce:
1. Load an STL and select a load surface and enter a Magnitude that does not equal 10.
2. Click Flip Direction. The Magnitude resets to 10.

Expected behavior: the value entered by the user should not change.

Build tested: https://teton-cdn.s3-us-west-2.amazonaws.com/smartslice-cura-plugin/dist/SmartSlicePlugin-r20.1-cyl-select.17.curapackage

**Comment by bradymadams** [comment]
This may be unique to the cylinder select branch. However, #55 is strongly related to this, so let's wait until that's done and then re-check this.

**Comment by bradymadams** [comment]
@rickdalgarno please test in latest 20.1 build

**Comment by rickdalgarno** [comment]
Tested and confirmed fix using SmartSlicePlugin-r20.1.34. Closing issue.
