### ISSUE TITLE
error when saving part without any smartslice data

### ISSUE THREAD

**Issue by colman-hartinger** [tetonsim/is-cura-ui#157]
When trying to save a file that doesn't have any smartslice data associated with it you get  "attribute error: NoneType has no attribute to dict ![saveerror.png](https://images.zenhubusercontent.com/5efa5ac65426339bbf817b5f/5dabba30-001d-44c2-acf5-b6d1ad52137e)[https://app.zenhub.com/files/209108148/aad65880-7cf9-4cd3-b73f-219d90da29d4/download](https://app.zenhub.com/files/209108148/aad65880-7cf9-4cd3-b73f-219d90da29d4/download)

**Comment by dougkenik** [comment]
Fixed in #158
