### ISSUE TITLE
Issue error when anchor and load surface are the same

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#197]
Currently, it is possible to define an anchor and a load on the same surface. The validation job will even run to completion.

This isn't critical for the MVP, but I suggest that the validate button should become "sick" when an anchor and a load are defined on the same surface.

**Comment by dougkenik** [comment]
@jake-kirkland-teton - check out `val.py` in `pywim\smartslice` I think this is where the error should originate from, just like all of the other lad and BC checks

**Comment by jake-kirkland-teton** [comment]
Closed by pywim PR #72.

https://github.com/tetonsim/pywim/pull/72
