### ISSUE TITLE
Remove print bed when user enters Smart Slice environment

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#2]

**Comment by thopiekar** [comment]
Also, based on master and working properly now!
When looking from the bottom the grid paper disappears :yum: 

![image](https://user-images.githubusercontent.com/1847437/65640793-741ee080-dfeb-11e9-8a4e-07525f3dbbf8.png)
![image](https://user-images.githubusercontent.com/1847437/65640835-88fb7400-dfeb-11e9-9ecc-348adb03a5c3.png)

**Comment by thopiekar** [comment]
@dougkenik Shall the boundary lines, the grid paper and the coordinate system disappear, too?

**Comment by dougkenik** [comment]
let's remove the graph paper and the boundary lines. keep the coordinate system

**Comment by thopiekar** [comment]
Ok. I see no trivial way to remove them, but will figure out.

**Comment by dougkenik** [comment]
if it will take too much time we can add another task and push it to the bottom of the priority list

**Comment by thopiekar** [comment]
Ok. Ask here for more info in the meantime:
https://github.com/Ultimaker/Cura/issues/6422

**Comment by nallath** [comment]
Sowwy, I forgot to commit the fix for both the platform and the build volume. Shame on me. It should be fixed for master now.

**Comment by thopiekar** [comment]
No problem. @dougkenik wanted to have the coordinate system displayed only, I guess it will be then about adding additional bools and skipping parts of the render function, right?

However, I'm running the current master and it works great:
![image](https://user-images.githubusercontent.com/1847437/65839655-ab550080-e30f-11e9-8507-5892dc24c6a1.png)
/home/thopiekar/Screenshots/Screenshot_20190929_231942.png
![image](https://user-images.githubusercontent.com/1847437/65839660-ba3bb300-e30f-11e9-8dea-1ca6400fca66.png)

**Comment by dougkenik** [comment]
I guess I couldn't say about how to go about it technically. For now we'll support one body and would like the CS displayed.
