### ISSUE TITLE
QTime does not handle print times that are greater than 24 hours

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#222]
If a print time comes back from Smart Slice as greater than 24 hours the conversion into a [QTime](https://doc.qt.io/qt-5/qtime.html) appears to "rollover" and drop the days, resulting in the wrong print time.

Related to https://github.com/tetonsim/smartslice/issues/125

**Comment by dougkenik** [comment]
For what it's worth - Cura does handle this in their Slice button, so I think we just copy whatever they did. Likely an oversight on my side

**Comment by dougkenik** [comment]
Note - use UM.Qt.Duration
