### ISSUE TITLE
Table headings on mac don't render properly

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#231]
From Mike.

![Screen Shot 2020-08-21 at 9.01.47 AM.png](https://images.zenhubusercontent.com/5ef37112bd138323ad7eea42/09e04dd1-86bc-4c2e-bd96-b62bc9b35c68)

**Comment by dougkenik** [comment]
Looks like this now:

![image.png](https://images.zenhubusercontent.com/5ef3733ee554441fdbf0d022/39742ef1-2d69-4905-be29-0f9ea2cfaf30)
