### ISSUE TITLE
Mod Mesh Not Displayed on Optimization Finished

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#263]
https://trello.com/c/jlgQoqU3/69-optimize-table-of-results-bug

**Comment by dougkenik** [comment]
@rickdalgarno - when I optimize this job and look at the results in the code, there is no modifier mesh in the first position (row 1). As I click through the rows, everything updates accordingly?

**Comment by rickdalgarno** [comment]
@dougkenik When I run the optimization, the mod mesh doesn't initially show up for rank 1. If you click on a different rank then go back to rank 1, it does show up.

**Comment by dougkenik** [comment]
> @dougkenik When I run the optimization, the mod mesh doesn't initially show up for rank 1. If you click on a different rank then go back to rank 1, it does show up.

I understand, but when I run it this behavior does not happen. When I ran it, there were no modifier meshes associated with the first result, and none appeared if i selected a different result and came back. In short, I cannot reproduce

**Comment by rickdalgarno** [comment]
@dougkenik Okay - I'll test this again when the next release candidate is ready to see if I can reproduce.

**Comment by rickdalgarno** [comment]
Here is a video that shows this bug:
[results_table_rank1_bug.zip](https://github.com/tetonsim/is-cura-ui/files/5175840/results_table_rank1_bug.zip)
