### ISSUE TITLE
The save warning dialog always comes up in the corner of the screen

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#266]
Would be a more common UX if it popped up in the center of the screen.

![image](https://user-images.githubusercontent.com/23110600/92280535-d5675900-eeb6-11ea-9630-379a7994bdae.png)

**Comment by dougkenik** [comment]
@bradymadams - I assume the About Box does this for you too? The x and y positions for these QML Dialogs are not set. However, this is the only time I have not seen them in the center of the screen

**Comment by bradymadams** [comment]
> @bradymadams - I assume the About Box does this for you too? The x and y positions for these QML Dialogs are not set. However, this is the only time I have not seen them in the center of the screen

Actually, the about dialog comes up dead center in the screen for me.
