### ISSUE TITLE
Track position of meshes

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#280]
Need to track the position of mod meshes and the other mesh in relation to one another, if status is optimized and a mod mesh exists on the build plate:

![MovingModelMeshBug](https://user-images.githubusercontent.com/23110600/92518999-85e69d00-f1d6-11ea-960e-29f1a095c716.gif)

**Comment by jake-kirkland-teton** [comment]
So if the bug that was created is not problematic for closing this ticket, and we want to handle the bug that was created in a separate ticket, I approve.
