### ISSUE TITLE
Modifier mesh location not read in correctly

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#297]
Modifier mesh was generated with SmartSlice, the position is below.

If I revalidate with the modifier mesh and save it, then open the file, the modifier mesh is not positioned on the build plate correctly:

[VALIDATED_TEST.3mf.zip](https://github.com/tetonsim/is-cura-ui/files/5209054/VALIDATED_TEST.3mf.zip)
![saved_position](https://user-images.githubusercontent.com/23110600/92927447-da6a6200-f3fa-11ea-95b1-0ef6dde0c7e1.png)
![opened_position](https://user-images.githubusercontent.com/23110600/92927452-db9b8f00-f3fa-11ea-9cce-767c3923958d.png)

**Comment by bradymadams** [comment]
@dougkenik is it only with manually added mod meshes or does it also occur with mod meshes from optimization?

This seems strange since we're not managing mod meshes during the saving and loading, right?

**Comment by dougkenik** [comment]
This happened after an optimization. I modified the modifier mesh density, then revalidated, and saved. When I open it up again, the mesh is out of place.

We do not handle their position, but we do create a ZOffset decorator for nodes from the optimization. It is likely happening from that

**Comment by bradymadams** [comment]
Okay, let's see what it takes to fix it.

**Comment by dougkenik** [comment]
I think what is happening is the plugin metadata isn't being cleared between saves. Verifying now - will take a while though

**Comment by dougkenik** [comment]
@rickdalgarno - let's document this as a known issue.

Here are the steps:

- User optimizes 
- Selects a result with a modifier mesh
- Changes anything to invalidate the results and continues
- Save the project
- Open the project

The modifier mesh will be positioned incorrectly in the Z location (looks like by about 1/2 of the modifier mesh)

**Comment by dougkenik** [comment]
I think the best option here would be to save the modifier meshes to our pywim.results object and then use the functions in SmartSliceProxy to remove any mod meshes and re-insert ours

**Comment by bradymadams** [comment]
> I think the best option here would be to save the modifier meshes to our pywim.results object and then use the functions in SmartSliceProxy to remove any mod meshes and re-insert ours

I agree that seems like a viable fix, but we should probably take a little time to understand more of what's going on with the transformations and the 3mfs before we commit to that.
