### ISSUE TITLE
Change left Menu to align with UX specs when user enters Smart Slice environment

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#3]

**Comment by dougkenik** [comment]
Left menu will change when user enters the Smart Slice environment, and the buttons will be inactive out. Once a user selects a body, the buttons will become active. This should function how the typical cura menu functions in Prepare

**Comment by thopiekar** [comment]
Works, but not really stable at the moment.
But it is useful enough to begin with the selection tool.
The Extruder selection buttons will be hidden later.

![image](https://user-images.githubusercontent.com/1847437/65839793-f3285780-e310-11e9-8600-79b75f865d65.png)

![image](https://user-images.githubusercontent.com/1847437/65839795-fe7b8300-e310-11e9-9dc2-44f6d4be6a88.png)
