### ISSUE TITLE
Draw arrow for Load normal to selected surface

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#30]

**Comment by dougkenik** [comment]
@aklempau - some issues I've noticed.

IN general, requirements for this ticket are [here](https://tetoncomposites.atlassian.net/wiki/spaces/CURA/pages/99582035/Load+Direction+Arrow). Let's continue to work towards these requirements and acceptance criteria.

1. The arrow is not being centered on the face. It appears you might be computing the center for one triangle, but not the aggregation of triangles which define the face. As an example, the center for the below face is at the center of the square.

![image](https://user-images.githubusercontent.com/24813209/73409804-896b8a80-42bd-11ea-9f86-580952fee625.png)

2. "Flip direction" is not working. If "flip direction" is not selected in the Load Dialogue, it should default to the arrow pointing towards the surface. If the user selects the "flip direction" radio button, it should change to pointing out

3. Color and size of the arrow need to change a bit. Something like this:
![image](https://user-images.githubusercontent.com/24813209/73410017-36de9e00-42be-11ea-8dcb-ef16e924a8c8.png)

I don't have a good idea of what "blue" we want yet (and I don't expect the shading), but if we should elongate the tail of the arrow and shorten the arrow head to match the picture.

**Comment by aklempau** [comment]
For "Flip Direction" radio button, should the arrow simply be drawn reversed by 180 degrees, or is it more involved than that?  Should the triangles themselves be drawn in a counterclockwise manner so that the normal direction of the triangle is changed?

**Comment by dougkenik** [comment]
Simply flipping by 180 will suffice. I don't think you need to redraw the triangles

**Comment by aklempau** [comment]
Pushed new changes to r20.0-load-normal-arrow branch.  The arrow is now centered on face.  If center is not touching portion of face, then arrow is centered over random triangle.  The flip direction checkbox is now working.

**Comment by dougkenik** [comment]
This is in PR #75

**Comment by dougkenik** [comment]
@aklempau - we also need to check that the arrow and force vector which is being sent with the smart slice job are pointed in the same direction, if you haven't already
