### ISSUE TITLE
Improve user experience for mesh analysis of complex geometries

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#311]
Originally reported by @rickdalgarno 

Steps to reproduce:
1. Open the attached STL and set the printer to an S5.
2. Scale it down to 25% so that it fits on the build tray.
3. Click on the Smart Slice stage. It takes a long time to process the STL and it appears to the user that something is hung up.

Proposed solutions in order of best to worst:
1. Figure out a way to process the model faster.
2. Messaging to inform user that the STL is loading into SS.

*The STL is the export frame which might be protected under an NDA*

**Comment by dougkenik** [comment]
Message can read:

"Analyzing Mesh" 

Message should appear when we start analyzing the mesh, and disappear when we're done

**Comment by dougkenik** [comment]
@colman-hartinger, I think UM has an option for showing a "working" updater in the message box - see the one presented on project open
