### ISSUE TITLE
Modifier mesh results ambiguous w.r.t. location

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#312]
Originally reported by @jlselden

> With a saved validation 3mf, the presentation of the models can be different if "Automatically drop models to the build plate" is checked when the file is opened as a project. The results are the same (see pics), but it is very non-intuitive.

![modmeshpos1](https://user-images.githubusercontent.com/23110600/92937741-f412a600-f408-11ea-9ae9-9a184b801422.png)
![modmeshpos2](https://user-images.githubusercontent.com/23110600/92937749-f5dc6980-f408-11ea-9226-0545bb7d723e.png)

**Comment by bradymadams** [comment]
@jlselden do you have that 3MF handy to attach here?

**Comment by jlselden** [comment]
This one works. 

[UMS5_dogbone_save4.zip](https://github.com/tetonsim/is-cura-ui/files/5241874/UMS5_dogbone_save4.zip)

**Comment by dougkenik** [comment]
@jlselden can you tell me the exact steps you took get the Validation file saved with the mesh in that location? Was it an optimization at first, or did you get the mesh there somehow, etc..

**Comment by jlselden** [comment]
I loaded the dogbone model. Then loaded the modifer mesh model (which I had lying around). Then performed a validation on it and saved that.

It was not a result from an optimization run. I was just playing with adding modifier meshes, validating, saving, and opening.

**Comment by dougkenik** [comment]
> I loaded the dogbone model. Then loaded the modifer mesh model (which I had lying around). Then performed a validation on it and saved that.
> 
> It was not a result from an optimization run. I was just playing with adding modifier meshes, validating, saving, and opening.

Ok, so when you brought in the modifier mesh model, did you move it to the desired location before validating? If so, was the Drop on Build Plate setting enabled?

**Comment by jlselden** [comment]
No, it wasn't. I had to turn that off in order to place the modifier mesh off the build plate.

**Comment by dougkenik** [comment]
> No, it wasn't. I had to turn that off in order to place the modifier mesh off the build plate.

Was it turned back on when you brought the models back in?

**Comment by jlselden** [comment]
I varied that. If it was off, everything was fine. If it was on, then the issue happened.

**Comment by dougkenik** [comment]
Ok, thanks. So it only happens if the setting is off, the project is saved, then the setting is on, and the project is opened

**Comment by jlselden** [comment]
Yes, that is what I saw.
