### ISSUE TITLE
3MF Loading Face Highlighting bug

### ISSUE THREAD

**Issue by jake-kirkland-teton** [tetonsim/is-cura-ui#329]
If you load in a 3MF with Optimization results, the boundary conditions do not highlight correctly. We either need to cause the print to go back to the prepare tab first when loaded, or figure out how to show the highlighting correctly.

**Comment by bradymadams** [comment]
To clarify this only happens when a 3MF is loaded while another project is loaded and the Smart Slice stage is active, right?

**Comment by jake-kirkland-teton** [comment]
That is correct. If you load a project from prepare or with no model on the stage you have to swap into Smart Slice so it is not a problem. Should have been clearer.
