### ISSUE TITLE
Strength and deformation result view buttons

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#342]
Create the buttons to activate the deformation and strength views per the mock-ups.

**Comment by dougkenik** [comment]
@jake-kirkland-teton - let's make sure the buttons do not appear if an optimization is successful

**Comment by jake-kirkland-teton** [comment]
@dougkenik For sure. And we don't want any of the popups to appear automatically either right? Also, do we only want the popup to dismiss if the user closes it, or clicks the Validate/Optimize? Or do we want it to disappear on settings changes and all of that as well?

Oh, and are the icons saved somewhere?

**Comment by dougkenik** [comment]
> @dougkenik For sure. And we don't want any of the popups to appear automatically either right? Also, do we only want the popup to dismiss if the user closes it, or clicks the Validate/Optimize? Or do we want it to disappear on settings changes and all of that as well?
> 
> Oh, and are the icons saved somewhere?

Popups should only display when the user selects the button. They should disappear when they select the other icon, are closed, or the user selects validate / optimize. They will disappear when the results are invalidated as well

Icons are in the shared drive:
https://tetoncompositescom.sharepoint.com/:f:/s/TetonSimulation/EpN6OO4aoyJDvdpltOAY1CMBc3vwpWKG-sGGjjyvXJo8MA?e=UwSWQO
