### ISSUE TITLE
Allow users to contact support when they have internet and cannot connect to Teton servers

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#352]
Large companies typically block access to external servers. We have seen a few users who cannot login after installation because the connection to our server is blocked by their IT.

We should issue a message to the user when this happens, and tell them our servers are being blocked, and that they should contact us.

**Comment by jake-kirkland-teton** [comment]
@dougkenik Do we know what the error code or error that comes in from this is?

**Comment by dougkenik** [comment]
No - we will need to dig

**Comment by jake-kirkland-teton** [comment]
Alright. After some testing and trying a few different things, I have found that there is not a lot we can differentiate from our connection error messages.

All of the connection errors cause a `HTTPSConnectionPool(host='api.smartslice.xyz', port=443):` exception, followed by a `Max retries exceeded with url:` error. From there, depending on the type of issue, a slightly different error is attached, but I have only been able to cause two types, and they are:
`NewConnectionError` and
`SSLError(CertificateError)`

We can design a message for the SSL error if we want, but I am not sure the average user will know what to do with that information at all.
As for the other message, it catches all connection issues, like no internet, server blocked or redirected and firewall blocking issues that I could create. And it would be very hard to split our responses to these errors. Additionally, these errors appear to be OS specific.

So I talked to Brady some, and I wanted to open the discussion up here as well. I believe that the best course of action moving forward will be to update our generic connection issue popup message to say something to the extent of:
Unable to contact the Teton Simulation servers. Check your internet connection, and if you are connected to the internet and still having trouble, please contact us at <Support URL>.
We can also throw something in about, contact your IT department or something too, but I assume it would be more effective to have them contact us, then we contact their IT? What are your guy's thoughts on this?

**Comment by dougkenik** [comment]
I think the proposed solution is fine. The error message should probably read:

"Unable to contact Smart Slice servers. 

Please check to ensure you have internet connection. If you do have internet connection, and are still receiving this error, please contact us."

The 'contact us' is the same hyperlink used in the "help" link for Extensions->Smart Slice-> Help
