### ISSUE TITLE
Smartslice stage error overlapping

### ISSUE THREAD

**Issue by AijunHall** [tetonsim/is-cura-ui#374]
See GIF. When a user has the error message box up, and changes a setting to an invalid one, the error message box won't extend in realtime. It only corrects once the user 'refreshes' the error message box by hovering over it again.

This can be reproduced a number of different ways - wherever a setting can be changed in one click with the error message box open at the same time basically.

[![Smartslice error overlapping](https://user-images.githubusercontent.com/54338983/104943776-18f4c800-596b-11eb-975d-b6d5b48fc32a.gif)](url)

**Comment by dougkenik** [comment]
Probably just need to do a forceLayout on the column which holds the errors after the activity is done. I think this is done through a signal
