### ISSUE TITLE
Analysis failed with custom print settings

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#377]
Running a job in Cura that has some customized settings. One (or more) of the customized settings is causing the analysis to fail when it's submitted. We should walk through each custom setting to see what is causing the issue.

![image.png](https://images.zenhubusercontent.com/5ef3733ee554441fdbf0d022/e3af3c26-e803-4ff3-a9ee-14160c79fb04)

**Comment by AijunHall** [comment]
Its the **Support** and **Build Plate Adhesion** Extruder settings. This specific analysis failure error comes up when these settings are not set to Extruder 1.

![image](https://user-images.githubusercontent.com/54338983/106328868-614a9a80-6235-11eb-8ab8-12e4a7b6fe0a.png)

![image](https://user-images.githubusercontent.com/54338983/106329397-314fc700-6236-11eb-9776-e2e93493382d.png)
