### ISSUE TITLE
Displacement Mesh CSYS Bug

### ISSUE THREAD

**Issue by jake-kirkland-teton** [tetonsim/is-cura-ui#388]
Similarly to Issue #367, we are seeing the displacement mesh displacing to the incorrect axis if the part is rotated in certain ways.

![image.png](https://images.zenhubusercontent.com/5efa5ada9e19f8d4e56a2b87/f413e691-46dc-4c1c-bcda-773604307f7a)

**Comment by dougkenik** [comment]
@jake-kirkland-teton please provide steps to reproduce

**Comment by dougkenik** [comment]
Does this happen for "problem meshes" too?

**Comment by jake-kirkland-teton** [comment]
Steps will be incoming, but I do not believe that the problem area meshes are affected the same way:

![image.png](https://images.zenhubusercontent.com/5efa5ada9e19f8d4e56a2b87/56b6e07a-2633-4a58-b8d5-56ef83cd3a72)

![image.png](https://images.zenhubusercontent.com/5efa5ada9e19f8d4e56a2b87/4c72294a-fe42-423f-8eb4-eb3a7a439f60)

**Comment by jake-kirkland-teton** [comment]
Steps to reproduce:

1) Load a project.
2) Rotate 90 degrees around the Cura Z axis
3) Apply a load/anchor
4) Validate
5) Click the displacement mesh button

![Bug388.gif](https://images.zenhubusercontent.com/5efa5ada9e19f8d4e56a2b87/9a0594ae-d1d4-46a3-a8fa-16615e9709f1)

**Comment by dougkenik** [comment]
@jlselden - this feels like the displacements are not being rotated when pushed back?

**Comment by jlselden** [comment]
@dougkenik It certainly does.

**Comment by jlselden** [comment]
@jake-kirkland-teton Does this happen if you only rotate it 45 degrees? Just curious.

**Comment by jake-kirkland-teton** [comment]
@jlselden Yes it does actually.

@dougkenik I take it back, I think it is hitting the problem meshes as well:

![image.png](https://images.zenhubusercontent.com/5efa5ada9e19f8d4e56a2b87/276e637d-900d-4711-a5df-edecc7724fae)

Rotated only 45 degrees, everything else exactly the same as the gif.

**Comment by jlselden** [comment]
@jake-kirkland-teton Here is what I'm seeing. First, I'm not seeing any problems running things on the backend, so I'm going to guess it could be a mismatch between the back and the front (as we suspected). Second, the transformations (centering AND rotation) are being sent to the backend as a single transformation, which is then being applied the mesh containing the displacement values. Third, in the first case above, i.e., the 90 degree rotation, the displacement is 90 degrees off what it should be. In the second case, i.e., the 45 degree rotation, the displacement "looks" 45 degrees off what it should be. Is it possible that the rotation is being added to the displacements when it gets returned to the front end?

Also, the problem meshes are fine for the 45 degree rotation case. The voxelization in that case is pretty rough, so everything looks really chunky.

**Comment by dougkenik** [comment]
We might be rotating the opposite direction?

**Comment by jlselden** [comment]
@jake-kirkland-teton Can you tell me what, if anything, happens to the meshes when they get sent back to the UI? I'm assuming that what is pictured in the UI is the original STL and that we are superimposing the displacement mesh on top of that, but maybe that's incorrect.

**Comment by jake-kirkland-teton** [comment]
@jlselden Of course. So the only thing that is happening is that a normalization is getting applied. Other than that, it is a straight adjustment to the existing mesh vertices. And you are correct, the images is the original STL with the displacement mesh superimposed on top. 

After a little research, and it's an early opinion, but I believe we are rotating the part, and then sending it with it's transformation, which the back end then uses to rotate the part again, which is why the angle ends up incorrect. I am not positive on this yet, but that is my current hypothesis.

**Comment by jlselden** [comment]
I agree that it looks like the rotation is being applied twice. I can confirm that the rotation is being combined with the other transformations (centering and -y/z swap) and that combined transformation is being sent to the back end.

**Comment by jlselden** [comment]
The fact that the bottom of the models lines up leads me to believe that it is an issues with the displacement coordinates.

**Comment by jlselden** [comment]
Do you have access to the rotation on your end?

**Comment by jake-kirkland-teton** [comment]
In what capacity? Because I believe so?

I am grabbing a couple screenshots real fast, I disabled the rotation of all loads and BC's for the moment, and that is nearly fixing this issue, but something strange is still going on.

**Comment by jake-kirkland-teton** [comment]
If I rotate the part 45 degrees:
![image.png](https://images.zenhubusercontent.com/5efa5ada9e19f8d4e56a2b87/b9ff4ad9-5b51-4246-893e-9d8991a9cd49)

And then run the validation:
![image.png](https://images.zenhubusercontent.com/5efa5ada9e19f8d4e56a2b87/9b4a94fd-d584-4627-8eae-77534c5c9673)

We get this displacement if I do not apply the rotation at all:
![image.png](https://images.zenhubusercontent.com/5efa5ada9e19f8d4e56a2b87/bfed53ff-56cc-47b0-9a4a-90f6ff853028)
![image.png](https://images.zenhubusercontent.com/5efa5ada9e19f8d4e56a2b87/fd48c671-50e0-4d96-9fdc-22ccb3c36ffd)

The displacement isn't quite in the right direction, and the problem meshes appear as if they hadn't rotated to match the part rotation.

**Comment by jlselden** [comment]
The problem regions require the full transformation to track the model, so that's why they are not in the correct place.

It seems that the force vector that gets sent to the backend is the rotated force vector, but it is acting on the unrotated part. So we get a force that is pushing the top down and left, which matches what we see.

**Comment by jake-kirkland-teton** [comment]
But if I do something on 90/180/270, such as rotate forward and lay flat:
![image.png](https://images.zenhubusercontent.com/5efa5ada9e19f8d4e56a2b87/0827155c-db62-4216-be3b-5915ab0ff11c)

Same BCs, just different rotation:
![image.png](https://images.zenhubusercontent.com/5efa5ada9e19f8d4e56a2b87/636ad24c-3edd-4d18-97ad-d06eac6fa43e)

We get an appropriate displacement without the front end rotation:
![image.png](https://images.zenhubusercontent.com/5efa5ada9e19f8d4e56a2b87/e530eda6-cdc3-4464-9836-9e5fdac650b9)

If I do EXACTLY the same thing, but apply the front end rotation we get this:
![image.png](https://images.zenhubusercontent.com/5efa5ada9e19f8d4e56a2b87/feab9dbb-9b4a-47c0-86ea-81adc8da949d)

**Comment by jake-kirkland-teton** [comment]
So I think I agree, we are currently sending the rotated force vector to the back end but something about the part is not getting rotated correctly. We were running into a similar problem with the load direction issue, the load vector was getting rotated, but the face was not, which is why we ran into that issue.

**Comment by jake-kirkland-teton** [comment]
Pause one second. I think I might be an idiot.

**Comment by jake-kirkland-teton** [comment]
Nope, that was not the issue. Nevermind, still not sure.

**Comment by jlselden** [comment]
What exactly do you mean by front end rotation?

**Comment by jlselden** [comment]
Actually, can you write out the displacements for one of these scenarios? I'd like to check it against the backend.

**Comment by jlselden** [comment]
I'm somewhat confused as to why a transformation would be applied to the load vector. Is the vector represented in global coordinates, or is it defined relative to the face it acts on?
