### ISSUE TITLE
Don't check support extruders if support is not enabled

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#393]
We should not be checking the support extruders if support is disabled. This was introduced in #399

**Comment by jake-kirkland-teton** [comment]
I assume on this one it is just prevent the 4 new extruder keys from being checked if the support is disabled?

**Comment by dougkenik** [comment]
Yes. Check out line 256-268 in ExtruderManager.py They do the checks here. I would do these same checks in SmartSlicePropertyHandler.py

**Comment by jake-kirkland-teton** [comment]
Would you add the checks in the __init__? I assume if we do this then we need to add a new connection to add and remove them from the property list as the extruder properties are changed. Or did you intend somewhere else? Do we want to prevent the support check in `_onSceneNodePropertyChanged` and just leave all of the keys in the global list?

**Comment by dougkenik** [comment]
Right now, it checks all of the `SmartSliceProperty.ExtruderProperty.KEYS` correctly, it just shouldn't check the support / adhesion ones based on if support / adhesion are selected. I would look at `SmartSliceProperty.SceneNodeExtruder` and maybe add a new list of keys to 'SmartSliceProperty.ExtruderProperty' which represent the support / adhesion ones
