### ISSUE TITLE
Displaced part/Failure location mesh does not toggle off while optimizing a part

### ISSUE THREAD

**Issue by faisal-bhuiyan** [tetonsim/is-cura-ui#400]
While optimizing a part, the displaced mesh or the failure location mesh does not toggle off once moved out of the functionalities of these "results" features and moving back into the "pre-processing" features - not sure if this is the intended behavior. The attached figure depicts the issue.

![image.png](https://images.zenhubusercontent.com/5efa5acd69fbe181aaf263a5/258b9800-934d-4fe8-87ca-c012132db88b)

Steps to reproduce the issue:
1. Validate a job and it returns the results with displaced mesh/problem region mesh depending on the validation output. 
2. Hit optimize - at this point the problem region buttons disappear (expected behavior).
3. Change scenes by going into the "Prepare" tab.
4. Now go back to "Smart Slice" tab - the problem region buttons reappear (_unexpected behavior_).
5. The problem region meshes could not be turned off at this point.

Please refer to the attached gif for more details.

![Issue400_steps](https://user-images.githubusercontent.com/59463700/107281984-a3cf5c80-6a17-11eb-8de1-121a4dfe8143.gif)

**Comment by faisal-bhuiyan** [comment]
Same thing happens on the validation task as described [in this issue](https://github.com/tetonsim/is-cura-ui/issues/407).

**Comment by jake-kirkland-teton** [comment]
Thank you for the update to the ticket! 

This is almost intended behavior. The meshes are supposed to show back up upon returning to the Smart Slice tab, however, the issue is that the buttons are not reappearing upon return to our tab. I will get that fixed.
