### ISSUE TITLE
Unexpected behavior when clicking SS menu on left side of screen

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#403]
As shown in the attached video, clicking on the menu on the left results in unexpected behavior. For example, when you click multiple times on the "?" button, the menu alternates between help and loads. When you click multiple times on anchors, the menu alternates between anchors and loads. When you click on loads, it always stays on loads.

Expected behavior: the menu always displays whatever you clicked on.

https://user-images.githubusercontent.com/34459028/107263047-8346d880-69fe-11eb-819f-ad703653a7ce.mp4

**Comment by dougkenik** [comment]
@rickdalgarno. This is how "tools" work in Cura - unfortunately. I'm closing this as a known issue
