### ISSUE TITLE
All BC faces highlighted on project open + erroneous highlighted face

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#404]
Steps to repro:
1. [Open this 3MF in Cura](https://github.com/tetonsim/is-cura-ui/files/5945922/bracket-highlighted-faces.3mf.zip)
2. Open Smart Slice

Notice that all of the BC faces are highlighted, which isn't expected. This isn't too bad as the highlighting still behaves well as you use the tool. But also notice the erroneously highlighted bottom face. I'm not sure if these two issues are related, but I'll group them together in this one issue until we find out more.

![bracket-highlighted-faces](https://user-images.githubusercontent.com/23110600/107265074-1123c300-6a01-11eb-8a2f-ec8d7f1af4e4.gif)

**Comment by dougkenik** [comment]
This is due to the question mark being the tool which is enabled when the stage switched to Smart Slice. 

1. That tool should only be enabled on first login
2. The faces should not be highlighted when that tool is selected
