### ISSUE TITLE
Deformed shaped and Failure locations pop-up boxes text formatting

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#405]
The pop-ups for the deformed shape and failure locations tools should be cleaned up in my opinion. 2 issues to address are provided in the annotated images below.

![pop-up-suggestions](https://user-images.githubusercontent.com/34459028/107266918-6c56b500-6a03-11eb-9a96-95783d40459e.png)

**Comment by faisal-bhuiyan** [comment]
Same observation for the following. We need to clean up the formatting of the text in the displayed message.

![Untitled](https://user-images.githubusercontent.com/59463700/107271373-5cda6a80-6a09-11eb-8415-eae72556b0bf.png)

**Comment by dougkenik** [comment]
I think this is machine and/or display dependent. It does not display this way display. We need to fix it
