### ISSUE TITLE
Displaced mesh and Failure Location mesh displayed at the same time

### ISSUE THREAD

**Issue by faisal-bhuiyan** [tetonsim/is-cura-ui#406]
The displaced mesh and the failure location mesh are shown concurrently when clicked on the "Show Displaced Part" button (does not happen for the "Show Failure Locations" button, as a relevant info). The expected behavior should to display on the displaced part when the mentioned button is clicked. Following figure illustrates the issue - 3mf attached to reproduce it.

![image.png](https://images.zenhubusercontent.com/5efa5acd69fbe181aaf263a5/f6317e08-f28f-4516-a877-0d47ac9e0934)

(https://app.zenhub.com/files/209108148/bc50bc95-a16a-403c-91a9-7c2327479a38/download)

**Comment by dougkenik** [comment]
@faisal-bhuiyan.if you read the pop-up, the red region highlights areas of high strain. The failure region might actually be a completely different region. Is this not clear?

**Comment by faisal-bhuiyan** [comment]
I missed the info in the text - it does make sense. I was expecting to see a different region for the too compliant part, which might not be reasonable for this case. I am closing this issue.
