### ISSUE TITLE
Different colors for the high-strain and failure regions

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#408]
Currently, the high-strain and failure region bodies are the same color (red). I suggest that they have different colors so that it is more clear to the user that these regions represent different things.

As a user, if I click on "Plot Deformed Shape", the high-strain regions are colored red. If I click on "Show Failure Locations", these regions are also red. Often, the high-strain and failure regions will have very similar shapes, so it is not always obvious to the user that they are looking at different things when the switch back and forth between the deformed shape and failure plots.

**Comment by faisal-bhuiyan** [comment]
I agree with the above observation - we can make it more obvious by providing visual cues via changing the color of problem areas according to the types of the problem regions.

**Comment by dougkenik** [comment]
Ok. Let's make the displacement problem regions dark blue
