### ISSUE TITLE
Error during optimization

### ISSUE THREAD

**Issue by colman-hartinger** [tetonsim/is-cura-ui#410]
Was running an optimization job that randomly reset

at 10:30 my validation finished and I started running an optimization job

![Screenshot 2021-02-08 13:29:23](https://user-images.githubusercontent.com/62404177/107277865-4389ec00-6a12-11eb-8c03-a9b3d28c6a9f.png)

than this hour I checked back on the job and it had started  running the optimization from the beginning again without any history of the previous optimization 

![Screenshot 2021-02-08 13:28:41](https://user-images.githubusercontent.com/62404177/107278019-7af89880-6a12-11eb-8ac0-c467539a7a75.png)

this was the error I got in the cura log that seemed to have triggered the reset

![bug](https://user-images.githubusercontent.com/62404177/107278189-a5e2ec80-6a12-11eb-905a-1f1faf839ffd.png)

Here is the part (I just selected import models instead of import project since this is an older save file)
[UMS5_drone_arm.zip](https://github.com/tetonsim/is-cura-ui/files/5946688/UMS5_drone_arm.zip)

**Comment by bradymadams** [comment]
The error message is unrelated. The issue with the optimization restarting is a known issue on the back-end, and there are existing tickets to address that eventually.
