### ISSUE TITLE
Sorting is broken in the optimization results table

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#411]
After optimization, sorting of results is not working properly. For example, open the attached Cura project file, go to the SS stage, and sort by Mass. The resulting sort is not correct. As shown below, the results are not sorted by mass.

Expected behavior: when sorting, results will be listed either from smallest to largest or largest to smallest.

![image](https://user-images.githubusercontent.com/34459028/107280951-425abe00-6a16-11eb-9d76-a16336b19b1d.png)

[UMS5_block_20x20x40.zip](https://github.com/tetonsim/is-cura-ui/files/5946811/UMS5_block_20x20x40.zip)

**Comment by colman-hartinger** [comment]
I'll also add to this that the tooltip text is sometimes cutoff for the optimization table
![tooltip](https://user-images.githubusercontent.com/62404177/107284792-83090600-6a1b-11eb-9f89-57acdb71d1e9.png)
