### ISSUE TITLE
Failure region popup text should not change when the user changes the FoS.

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#429]
Currently, a user can plot the failure regions. The regions that are plotted depend on the FoS value entered by the user when the job was submitted. If the user plots the failure regions, then changes the FoS value and replots the failure regions, the failure regions do not change. However, the popup text does change and it implies the region now corresponds to the updated FoS.

Workflow:

1. Define a FoS of, for example, 1.5.
2. Run a validation.
2. Plot the failure regions. Note that the popup says "The areas shaded in red have... value of 1.5".
3. Change the FoS to, for example, 1.3.
4. Plot the failure regions again. Note that the failure regions are the same as from step 2 but the popup says "The areas shaded in red have... value of 1.3.

Expected behavior: When the user changes the FoS, the popup should continue to display "The areas shaded in red have... value of _original FoS_".

Important: We don't want to reset the validation results when a user changes the FoS. It is common for a user to run a validation, THEN define the FoS for the optimization.

Config: Cura 4.7 and release candidate 2.

**Comment by dougkenik** [comment]
I think we just reset the validation if the user changes these values

**Comment by rickdalgarno** [comment]
> I think we just reset the validation if the user changes these values

I really don't think the FoS value should reset the validation results. The FoS is just a target for the optimization - it has no effect on the computed FoS or the computed displacement. We shouldn't make a user run a second validation just because they didn't enter a FoS before the validation.

**Comment by dougkenik** [comment]
> > I think we just reset the validation if the user changes these values
> 
> I really don't think the FoS value should reset the validation results. The FoS is just a target for the optimization - it has no effect on the computed FoS or the computed displacement. We shouldn't make a user run a second validation just because they didn't enter a FoS before the validation.

The problem with this is that the value the user enters is used in a lot of various places and continuously updated (including the popup). If we go this route, we will need to keep track of the original value the user entered and the new value

**Comment by rickdalgarno** [comment]
> > > I think we just reset the validation if the user changes these values
> > 
> > 
> > I really don't think the FoS value should reset the validation results. The FoS is just a target for the optimization - it has no effect on the computed FoS or the computed displacement. We shouldn't make a user run a second validation just because they didn't enter a FoS before the validation.
> 
> The problem with this is that the value the user enters is used in a lot of various places and continuously updated (including the popup). If we go this route, we will need to keep track of the original value the user entered and the new value. In other words, it could be a decent amount of work. I don't see an issue with resetting the validation if the user changes the value

I understand that it is more work for us but it will be a better user experience. Reppin' the cuztomer...

**Comment by dougkenik** [comment]
I honestly think it could cause more confusion than not if we update the max FoS in all of the other dialogues (slice button popup, requirements, etc.) and keep it the same in the message for the factor of safety. This is my opinion, and we can talk as a group, but I think the better user experience is to revert back to Validate when these properties are changed so the user can re-validate and see the new problem meshes - then optimize
