### ISSUE TITLE
Mod meshes are duplicated and translated when opening .3mf from SS version 20.1

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#431]
Steps to reproduce:

1. Install SS 20.1.
2. Run an optimization. Save the project.
3. Install 20.2 release candidate 1 or 2.
4. Open the .3mf from step 2.
5. The modifier meshes from the optimization will be (a) duplicated and (b) the duplicate set will be translated.

Expected: the mod meshes are in the same position as they were in 20.1.

The following screenshots show the optimized part from step 2 (SmartSlicePlugin-r20.1.103) and the optimized part from step 4 (SmartSlicePlugin-r20.2.44). The 2nd image clearly shows that the mod meshes were copied and translated.

Optimized .3mf from 20.1:
[optimized_side_orientation.zip](https://github.com/tetonsim/is-cura-ui/files/5962367/optimized_side_orientation.zip)

![image](https://user-images.githubusercontent.com/34459028/107587198-8d173a00-6bbe-11eb-8776-2751d72eaf01.png)

![image](https://user-images.githubusercontent.com/34459028/107587253-97393880-6bbe-11eb-9bd7-0dcd5581b129.png)

**Comment by dougkenik** [comment]
@jake-kirkland-teton - I thought we tested this?

**Comment by jake-kirkland-teton** [comment]
We absolutely did. And fixed it last release if I recall correctly.
