### ISSUE TITLE
Place modifier meshes from Smart Slice result into Cura scene 

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#44]

**Comment by dougkenik** [comment]
Workflow:

- Optimization returns a success, and info is displayed in pop-up
- Slice button changes to "Preview" (mod meshes are not placed in scene yet)
- User clicks preview
- We create mod meshes, place them on the build plate, reslice, and push the user to "Preview" stage

**Comment by bradymadams** [comment]
The returned Smart Slice Result class is defined here: https://github.com/tetonsim/pywim/blob/r19.1/pywim/smartslice/result.py#L21

That's what comes back from a successful Smart Slice. Here's some pseudo/Python code for how the modifier meshes can be accessed:

```
# we should only have one analysis
if len(result.analyses[0]) != 1:
    raise an exception?

analysis = results.analyses[0]
for mesh in analysis.modifier_meshes:
    use mesh.vertices and mesh.triangles to create modifier mesh in Cura scene
    set new mesh to "Modify settings for overlaps" on "Infill Only"
    use mesh.print_config.infill.density and mesh.print_config.infill.pattern to set the Infill Density and Pattern settings for the new modifier mesh
```

This is how the modifier mesh should be configured:
![image](https://user-images.githubusercontent.com/23110600/68994056-aa364f00-083b-11ea-813b-e0d5f5ba9643.png)

Here's the Mesh class: https://github.com/tetonsim/pywim/blob/r19.1/pywim/chop/mesh.py
It inherits from the threemf Mesh class: https://github.com/tetonsim/py3mf/blob/master/threemf/mesh.py#L15
