### ISSUE TITLE
Solver erroring out not being able to apply a boundary condition

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#452]
See model below. Chop is exiting with an error that is cannot apply the anchor:

https://tetoncompositescom.sharepoint.com/:u:/s/TetonSimulation/EfTUsxLzNW5PjH8kPIkmcu8Be_qzHQN2zR9-fBAmNav6_g?e=61x92B

**Comment by faisal-bhuiyan** [comment]
@dougkenik Could not open the attached link.

**Comment by dougkenik** [comment]
@faisal-bhuiyan - fixed

**Comment by dougkenik** [comment]
See #327

**Comment by bradymadams** [comment]
See https://github.com/tetonsim/wim/issues/327

**Comment by faisal-bhuiyan** [comment]
> See #327

@dougkenik How are these issues connected? Maybe you meant the issue Brady attached above?

**Comment by dougkenik** [comment]
Yes, I meant that one. My fault

**Comment by faisal-bhuiyan** [comment]
No worries, I think wim is the best repo for dealing with this issue.
