### ISSUE TITLE
Load arrow doesn't return to original position on "Cancel"

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#459]
When running a Validation, if you move the load arrow via the manipulation wheel, it will trigger a "Cancel/Continue" option for the user. If you click Cancel, the arrow does not return to the original position.

Steps:

1. Define a load where the load manipulation wheel is present.
2. Start a Validate.
3. During the Validate solution, adjust the load angle arrow. When prompted to Cancel or Continue, click Cancel. The arrow does not return to the original position.

Expected: the arrow returns to the original position after clicking Cancel.

See video below.

Tested with Cura 4.7 and r20.2 RC6.

https://user-images.githubusercontent.com/34459028/108270501-c7d42180-712c-11eb-8540-c41fd02cef07.mp4

[UMS5_shelf bracket_wheel_cancel.zip](https://github.com/tetonsim/is-cura-ui/files/5998721/UMS5_shelf.bracket_wheel_cancel.zip)

**Comment by rickdalgarno** [comment]
IMO, this is not critical and can be pushed to a later release.

**Comment by bradymadams** [comment]
I can repro this. It's definitely strange behavior. It happens about 1/2 the time, and if you move and cancel it several times it will eventually revert back to the original, correct position. We'll look into fixing this for the 20.2 release if something else critical comes up that we need to fix.
