### ISSUE TITLE
Cura Crashes with infill angles undefined

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#468]
From a customer - log files attached.

Details: from a previous job, raster angle was set to 0/90. I imported the model, opened Smart Slice, selected fixed face, selected load surfaces and when validating, the error of infill line direction appeared. I changed the angle and then it crashed. I did the same once more and it happened again.
I changed the angle before starting Smart Slice and again I had the crash. After that, Smart Slice stopped working. I reinstalled the plug, but no change - it still does not work.

[https://app.zenhub.com/files/209108148/6d44b8a0-7609-4b0f-8cbb-66a77dc25bbe/download](https://app.zenhub.com/files/209108148/6d44b8a0-7609-4b0f-8cbb-66a77dc25bbe/download)

**Comment by bradymadams** [comment]
I believe this issue was fixed in the 20.2 release. #373

**Comment by dougkenik** [comment]
Fixed in #373
