### ISSUE TITLE
0 Infill Density Is Allowed

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#492]
A user can enter 0 for infill density, and we do not issue a warning

**Comment by dougkenik** [comment]
@AijunHall - I didn't see this in "In Progress" in the Zenhub Board, so I fixed it while you were working on it. I added you as a reviewer

**Comment by bradymadams** [comment]
This was fixed in https://github.com/tetonsim/pywim/pull/84
