### ISSUE TITLE
Fatal error when turning on support after an optimization

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#498]
After an optimization, if you toggle on the "Support" print parameter, and then "Cancel" the prompt that appears, a fatal error occurs. 

Steps:
1. Open the attached .3mf. This file was saved after an optimization completed.
2. In the print settings, toggle on the "Support" parameter.
3. Click "Cancel" in the SmartSlice prompt that appears.
4. A fatal crash occurs.

Notes:
-  the crash does not occur if you click "Continue" in step 3.
- This was reported by a reseller. They were trying to understand how to print a part with supports after an optimization since we don't support extruder 2.

![fatal_error](https://user-images.githubusercontent.com/34459028/113942664-693b3380-97be-11eb-8ada-21f5b25fedda.gif)

[optimized_side_orientation.zip](https://github.com/tetonsim/is-cura-ui/files/6274837/optimized_side_orientation.zip)
[stderr.log](https://github.com/tetonsim/is-cura-ui/files/6274866/stderr.log)

**Comment by bradymadams** [comment]
@rickdalgarno the stderr.log doesn't have any errors in it. Are you sure you grabbed it after closing Cura and you didn't reopen Cura before retrieving it? It only has about 30 seconds worth of activity.

**Comment by dougkenik** [comment]
@rickdalgarno - I can reproduce in the Prepare stage, but not the SmartSlice stage. Can you verify, as this might be the short term workaround

**Comment by rickdalgarno** [comment]
Resolved with PR #501. The "Generate Support" parameter is no longer tracked by SmartSlice.
