### ISSUE TITLE
Load magnitude tooltip in custom is cutoff

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#518]
This is on a maximized window on a common resolution of 1920x1080. Also looks like it's referring to "pictures" which are deactivated in the custom selection.

![image](https://user-images.githubusercontent.com/23110600/116586356-9ae37e00-a8d6-11eb-98aa-76c726ae7eff.png)

**Comment by faisal-bhuiyan** [comment]
Data point from cura v4.8 on windows. The tooltip is not cutoff, however, the description is incorrect since its referring to the load magnitude helper pictures.

![LoadMagTooltip](https://user-images.githubusercontent.com/59463700/116609763-ff600680-a8f1-11eb-95e3-e3fcd48f76a5.png)

**Comment by rickdalgarno** [comment]
Related: the mini tooltip for the Loads icon is partially covered by the loads window. 

![image](https://user-images.githubusercontent.com/34459028/116612497-db51f480-a8f4-11eb-9232-b853873707e6.png)
