### ISSUE TITLE
Deselecting model during validation causes "Lose results" popup

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#522]
Not sure if this is unique to the model, custom surface selection or what, but there's two issues here. One, just deselecting the model causes the "lose results?" popup to come up. And clicking cancel and then reselecting the model causes it to come up again.

The second issue can also be seen in the gif if you watch the load arrow. After clicking cancel the arrow direction changes (both graphically and the vector components change).

[PI3MK2_Dog_Butt_Wall_Hanging_Final.zip](https://github.com/tetonsim/is-cura-ui/files/6401519/PI3MK2_Dog_Butt_Wall_Hanging_Final.zip)

![custom-load-arrow-cancel](https://user-images.githubusercontent.com/23110600/116615438-89ab6900-a8f8-11eb-8c2d-8f63815473cf.gif)

**Comment by dougkenik** [comment]
I think this is related to #518

**Comment by bradymadams** [comment]
> I think this is related to #518

@dougkenik did you mean #519?

**Comment by dougkenik** [comment]
Yes - apologies
