### ISSUE TITLE
SmartSlice job state management

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#53]
- [x] Design the full user experience for validation and optimization workflows
- [ ] Implement logic to track the SmartSlice state to support full validation and optimization workflows

**Comment by dougkenik** [comment]
Validation mockups are here:
https://tetoncompositescom-my.sharepoint.com/:p:/g/personal/doug_kenik_tetonsim_com/EZ2BctkN4FRJrjhmYrVPekYBQ03syG0Y_qJuHD3EDOjB_Q?e=JQZNa6

**Comment by dougkenik** [comment]
Optimization mockups are here:
https://tetoncompositescom-my.sharepoint.com/:p:/g/personal/doug_kenik_tetonsim_com/EYl9uVCv90ZHr-RHyuk4v0cBpc7zly9Sh9hDe3DGTjkiFA?e=30fbfl

**Comment by dougkenik** [comment]
@CodyFagley - do you need some definition around which settings should trigger an event? I do not know if we ever defined this

**Comment by dougkenik** [comment]
@CodyFagley, updated settings which should impact validation/optimization workflows:
https://tetoncomposites.atlassian.net/wiki/spaces/CURA/pages/99549204/Validation+Workflow

**Comment by CodyFagley** [comment]
## Known Issues
**Background Information**
Many settings (properties) have dependencies (other settings which have values that change).  

**Issues**
*  When global/extruder changes are "cancelled" during validation/optimization, the settings are automatically set to their previous value
    *  This causes Cura to trigger a redundant onChanged signal when it shouldn't.
    *  Additional prompts are raised for each dependency and must all be closed to revert each setting back.
*  There are consistency glitches that are tough to explicitly reproduce
    *  Hypothesis: Changes in Cura's data are occurring without updating the cache contained in [SmartSlicePropertyHandler](https://github.com/tetonsim/is-cura-ui/blob/cf-r20-UI-Validation/SmartSlicePlugin/SmartSliceExtension/SmartSlicePropertyHandler.py#L44)

**Comment by dougkenik** [comment]
So if I run a validation, change a setting when the validation is running, and then resubmit the validation, I get the below error. We should just sever the current job when a user knowingly moves forward with a setting change, and then allow them to resubmit whenever they want

![image](https://user-images.githubusercontent.com/24813209/73234051-bb59e100-4145-11ea-8ec0-be1fd92f0d90.png)

**Comment by dougkenik** [comment]
@CodyFagley - we should allow users to change Max Displacement and/or FoS when a job is validating without prompting them to cancel or continue.

However, if either of those two are changed during an optimization run, we should ask the user to cancel or continue as they definitely do affect the optimization results

**Comment by dougkenik** [comment]
@CodyFagley - with the new build (Validation-17), if I change the Wall Line Count or # Top/Bottom layers during a validation, and Cancel the change, the numbers do not revert back to the original values.

Also, I am routinely having to select "Cancel" multiple times before the dialogue dismisses

**Comment by dougkenik** [comment]
@CodyFagley - with the new build (Validation-17), if I validate the first time, then change a parameter and re-validate.... the dialogue for Cancel or Continue pops up and disappears, and then the button on the bottom right switches back to Validate. There is no path to get to optimization

**Comment by dougkenik** [comment]
@CodyFagley In Validation-18 I'm still having to select "Cancel" more than once. The first time will revert the value, and the second time will dismiss the dialoague

**Comment by dougkenik** [comment]
@CodyFagley  In Validation-18, if I change the Wall Line count and re-validate, the results come back the same. Need to check this

**Comment by dougkenik** [comment]
@CodyFagley  - In Validation-18,  if I cancel an optimization job, and I have not changed any parameter which does not influence our solution, I would think it would not revert to "Validate" and allow me to "Optimize"

If I change a parameter, it should revert to "Validate"

**Comment by dougkenik** [comment]
@CodyFagley - In Validation-18, the results of an "optimization" are displaying "green" as good, but no values have changed from the validation:

![image](https://user-images.githubusercontent.com/24813209/73411018-2d0a6a00-42c1-11ea-9b5e-21674ed961cd.png)

**Comment by dougkenik** [comment]
@CodyFagley - In Validation-18... if I change a parameter after optimization, it immediately switches to "Validate." I would expect the "Cancel" or "Continue" button to pop up (as in requirements)

We should be working to the mockups I posted, and these requirements:

https://tetoncomposites.atlassian.net/wiki/spaces/CURA/pages/99549204/Validation+Workflow
https://tetoncomposites.atlassian.net/wiki/spaces/CURA/pages/99549245/Optimization+Workflow

**Comment by CodyFagley** [comment]
> @CodyFagley In Validation-18, if I change the Wall Line count and re-validate, the results come back the same. Need to check this

I can confirm that Wall Line Count is not changing the resulting Factor of Safety or Max Displacement, while I have identified where Wall Line Count is getting set in the `pywim.am.Config()` object:
https://github.com/tetonsim/is-cura-ui/blob/cf-r20-UI-Validation/SmartSlicePlugin/SmartSliceCloudConnector.py#L978

In the following line, I have added the print statement so I could test the number against expected output (see results below).  Wall Line Count seems to be set to the expected number and is not altered anywhere else in the file so I am not sure where this problem lies.  @bradymadams  do you have any pointers on other things I should check?  Thanks!!

```
WALL LINE COUNT CHECK:  4

WALL LINE COUNT CHECK:  8

WALL LINE COUNT CHECK:  4
```

Finally a list of settings affected/unaffected:
**Settings that DO NOT affect validation results**
* Wall Thickness
* Wall Line Count
* Top & Bottom Layers
* Skin Angles

**Settings that affect validation results**
* Anchors, Loads, Magnitude, Direction
* Line Width, Layer Height
* Infill Settings
*

**Comment by bradymadams** [comment]
@CodyFagley If you can get the 3MF files that are sent to the cloud for the wall line count 4 and 8 configurations I can take a look at them to see if it's a problem with the plug-in populating the 3MF correctly, or a problem in the smart slice engine.

**Comment by CodyFagley** [comment]
> @CodyFagley If you can get the 3MF files that are sent to the cloud for the wall line count 4 and 8 configurations I can take a look at them to see if it's a problem with the plug-in populating the 3MF correctly, or a problem in the smart slice engine.

Thanks Brady!  I'll start with this today and ping you on slack.

**Comment by bradymadams** [comment]
@CodyFagley @dougkenik I looked at the 3MF files and the problem boils down to the wall_line_count setting being set to a lower value on the extruder configuration. It's fine if that statement doesn't make total sense to you. But what I tried to do is figure out how that's happening, and I can't reproduce the problem. I think it has something to do with the print setup in Cura. For the 8 wall count job can you save the 3MF through the File -> Save menu? I'd like to open it in Cura and see what's different about the way you guys are setting up the print.

**Comment by CodyFagley** [comment]
Yup!  Thanks for looking that over, Brady!  

I will provide a response this afternoon.

**Comment by bradymadams** [comment]
I loaded each of the 3MFs @CodyFagley sent me, setup the same Smart Slice job, validated them and I got different results:

![image](https://user-images.githubusercontent.com/23110600/73891474-83335c00-4831-11ea-886f-168bcceebcac.png)

The differences are what I would expect. Additionally, I manually chopped the 8 wall job and looked at the polygons and confirmed it was sliced with 8 walls.

I'm unable to determine how the original 3MFs were created that showcased the problem. Perhaps, the problem is unique to the branch Cody is currently working in. I tried to test on Cody's branch, but I needed to merge r20.0 in order to test locally, and I couldn't get a proper merge. I'm not sure how to proceed. If someone could do a screen record showing how to setup the problem to trigger the bug that would help me.

**Comment by bradymadams** [comment]
@CodyFagley @dougkenik I tracked down the problem it is (kind of) unrelated to this issue. The reason I say it's kind of unrelated is because the issue has always been there, we just haven't noticed it because we could never do multiple validations before. Normally, I would say we should open a new issue and handle it separately, but I appreciate this is important to verifying the work in this branch.

@CodyFagley the issue is with `SmartSliceCloudConnector._all_extruders_settings` the slice settings are cached the first time they're used and never updated to reflect any changes to the print settings. I don't know the best fix, but here's two possible approaches:

1. Remove the cache functionality altogether and always compute the settings when they're needed. This is probably the safest fix, but I'm unsure if computing the settings is expensive enough that the cache is necessary.
2. Set _all_extruders_settings to None whenever a setting is changed. This would be _any_ setting, not just the ones we're interested in for smart slice.
