### ISSUE TITLE
Changing load on validate model doesn't revert status back to unvalidated

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#533]
Cura 4.9

1. Open 3MF attached to #522 
2. Go to SmartSlice and notice the model is validated already
3. Click a different surface to move the load. At this point the load surface changes, but the ready to optimize status remains and the pop up to confirm changes never comes up.
4. Now click another surface to move the load again. It will now revert back to un-validated.

Additionally the validate button looks like this. Not sure if this is related:

![image](https://user-images.githubusercontent.com/23110600/117186911-94eb1280-ad98-11eb-937d-c88313b6ebd4.png)

**Comment by jlselden** [comment]
@bradymadams I don't see the 3mf.

**Comment by bradymadams** [comment]
> @bradymadams I don't see the 3mf.

@jlselden it's attached to the description in #522

**Comment by jlselden** [comment]
I am a dumbass.

**Comment by dougkenik** [comment]
If I follow these steps, I cannot even select a different surface when I open the optimized model.

**Comment by rickdalgarno** [comment]
+1 to the image in this ticket. I've also seen the "extra space" above the Validate button after triggering a change.

**Comment by jlselden** [comment]
I can repro everything in 4.8 except the extra white space. 
![image](https://user-images.githubusercontent.com/9937246/117201479-89501980-ada1-11eb-805f-18d3f4f8671f.png)

**Comment by jlselden** [comment]
Also, there's something weird going on with the loads. There are 2 "Load 1" and the first one seems empty.
![image](https://user-images.githubusercontent.com/9937246/117201754-dcc26780-ada1-11eb-9001-6136adfd6964.png)

**Comment by jlselden** [comment]
One more thing. When I open the 3mf, the model isn't optimized. It has been through the Validation cycle and there is a request to Optimize. So the behavior I'm seeing is similar though maybe not identical to what's described above. Changes the surfaces the first time, for either anchor or load,  doesn't change the Optimize button. The second surface change resets validate.

**Comment by jlselden** [comment]
Ok. So this behavior is somewhat robust. I optimized (re-optimized?) the dog butt and I can do the same thing, i.e., choose a different surface with no prompt. Then choose another surface and get the prompt. I can cancel, which takes me back to the original force and repeat the exact same process. Here are some screen shots.
![image](https://user-images.githubusercontent.com/9937246/117211278-a559b800-adad-11eb-83d5-fd2210b788e8.png)
![image](https://user-images.githubusercontent.com/9937246/117211317-b0ace380-adad-11eb-90f4-a53c2dbb4fce.png)
![image](https://user-images.githubusercontent.com/9937246/117211346-b99db500-adad-11eb-865d-a83a4c223ccb.png)

**Comment by dougkenik** [comment]
I believe everything besides the white space in the validate button is tied to the same thing.

For some reason, Cura is not even emitting a selectedFaceChanged signal when a face is clicked, which means our system is not getting called. This only happens after a project open.

**Comment by dougkenik** [comment]
Ok - so here is the example. The below picture is after an optimization. Note that this is not a "Group"

![image](https://user-images.githubusercontent.com/24813209/117304795-fd86cd80-ae32-11eb-84c6-11084bbd3dc1.png)

If we open a project that's been optimized, this is a "Group." It looks like Cura adds a "Group" decorator when the models are read in, and that is what is causing the issues.

![image](https://user-images.githubusercontent.com/24813209/117301681-b945fe00-ae2f-11eb-8c92-8d9f7344a9cb.png)
