### ISSUE TITLE
Display issue in "Material Estimation"

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#535]
In the Material Estimation results, the length value overlaps the mass value. This is a part with over 1,000 g of material, so there are 4 digits left of the decimal point. Probably a simple fix.

![Picture1](https://user-images.githubusercontent.com/34459028/117199976-1ac28a00-ada8-11eb-9013-53f9ed80ddc8.png)

**Comment by dougkenik** [comment]
@rickdalgarno do you have this job?

**Comment by rickdalgarno** [comment]
> @rickdalgarno do you have this job?

https://tetoncompositescom.sharepoint.com/:f:/s/TetonSimulation/EkqpK4Tgje1MheOoAzrOUrwBw3YAntM8dIi_UM9VUQ40Iw?e=4oA6H3
