### ISSUE TITLE
Duplicate anchors/loads when opening validated 3MF

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#538]
I'm not entirely sure of the steps necessary, but see [this comment](https://github.com/tetonsim/is-cura-ui/issues/533#issuecomment-832969320) for some info. I noticed it a couple of times when working on #533.

[PI3MK2_Dog_Butt_Wall_Hanging_Final.zip](https://github.com/tetonsim/is-cura-ui/files/6401519/PI3MK2_Dog_Butt_Wall_Hanging_Final.zip)

**Comment by jlselden** [comment]
I'm not sure what I did to get that either. I can try to play around some more.

**Comment by dougkenik** [comment]
@jlselden - what Cura version were you using? I cannot reproduce

**Comment by jlselden** [comment]
Cura 4.8. I have had it happen a few times, but I can't determine the cause or sequence of causes in order to reproduce it.

**Comment by jlselden** [comment]
@dougkenik 
Ok. I think I have a way to reproduce it.
1. Drag and drop the 3mf into Cura.
2. Choose to open as a project and select "open" in the project summary.
3. Wait for the loading popup to finish.
4. While the SmartSlice geometry analysis popup is **still up**, click on the SmartSlice tab.
5. There will be either an extra (empty) Anchor 1 or and extra (empty) Load 1.

I think the extra anchor or load depends on which thing you were looking at last in SmartSlice, but I'm not sure.
