### ISSUE TITLE
Detect existing modifier meshes

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#54]
Detect if modifier meshes are present when a SmartSlice job is submitted. If so, for an optimization, ask the user if they want to proceed and have the meshes removed.

**Comment by dougkenik** [comment]
Mockup for the warning is in this deck:
https://tetoncompositescom-my.sharepoint.com/:p:/g/personal/doug_kenik_tetonsim_com/EYl9uVCv90ZHr-RHyuk4v0cBpc7zly9Sh9hDe3DGTjkiFA?e=30fbfl

**Comment by thopiekar** [comment]
Please take a look where the meshes are created. I remember that I give the meshes a specific name, which can be used to find them.

**Comment by CodyFagley** [comment]
This has been resolved by newest 2 commits into UI branch. (Merged from r20-UI-ModifierMesh)

Currently, it is checking during validation, but the same logic should be moved/used in Optimization when Smart Slice includes modifier mesh validation.
