### ISSUE TITLE
Validate button remains sick after addressing item to be resolved

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#541]
Steps:
1. Replace the material database file with the file here (the issue is with a new tested material so the existing matDB file doesn't have the GUID): https://tetoncompositescom.sharepoint.com/:f:/s/TetonSimulation/El8VVKr-PNBHjk1UVgKtgBkB1l6GyIXbdd-yYHVxtYUq9A?e=EgK8Ye
2. Open Cura and setup a basic validation using generic ABS. 
3. Switch the material to Jabil PA0600 (will need to install from the Cura Marketplace). Notice the Validate button goes sick.
4. Resolve the issues in the Validate warning message.
5. The button remains sick.

If you change another print parameter (infill density, for example), then the button goes unsick.

https://user-images.githubusercontent.com/34459028/117508559-09af7f80-af46-11eb-8f9f-9494defbb9d7.mp4

**Comment by dougkenik** [comment]
@rickdalgarno - Was this in 4.9?

**Comment by rickdalgarno** [comment]
@dougkenik Roger that. I don't think it is a big deal as these print parameters are set to lines for nearly every other material in our database so this issue is more or less specific to this material. However, if we ever do a case study with Jabil on this material, then it would be good to fix this issue.
