### ISSUE TITLE
Load example covers tool tips

### ISSUE THREAD

**Issue by Tyler-Heckenlively** [tetonsim/is-cura-ui#545]
Once you use the load magnitude slider the example stays on screen. This covers the tool tips information. 

![image (3)](https://user-images.githubusercontent.com/69323579/117855706-f94e1c00-b247-11eb-9066-a5446916ff61.png)

**Comment by rickdalgarno** [comment]
I thought I mentioned this in a different issue but I'll repeat it here since it is closely related. The Load tooltip is behind the load selection window.

![image](https://user-images.githubusercontent.com/34459028/117856532-f7d12380-b248-11eb-8b00-78eb2688e0a1.png)

**Comment by dougkenik** [comment]
@rickdalgarno - they appear related, but they are actually not. The first issue is easily solvable and the second will take a lot more effort.
