### ISSUE TITLE
Multiple loads/anchors

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#55]
- [x] Design UX
- [ ] Implement

**Comment by dougkenik** [comment]
User experience is being defined here:
https://tetoncompositescom-my.sharepoint.com/:p:/g/personal/doug_kenik_tetonsim_com/Eb__yJym1ghHoVY5tbvUtSMB0yQaPMbR-dI86N_0h65zMg?e=ffyiFG

**Comment by bradymadams** [comment]
@colman-hartinger see the r20.1-multiple-bcs-cherry branch. That contains a lot of work already done for this issue. I started on it several months ago, but wasn't able to finish it. I just merged r20.1 into it this morning so it is up to date with all of the latest changes.

**Comment by bradymadams** [comment]
Note that the 5 story point estimate considers that much of the work is already done.
