### ISSUE TITLE
Interactive results table

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#58]
Create a table to allow user to view and interact with multiple optimization results

**Comment by dougkenik** [comment]
Should use these functions for defining the table and it's appearance. They seem to have everything we would need for the appearance and sorting/filtering:

https://doc.qt.io/qt-5/qml-qtquick-controls-tableview.html
https://doc.qt.io/qt-5/qml-qtquick-controls-styles-tableviewstyle.html
