### ISSUE TITLE
Wrong color scheme used for validation results in dark theme

### ISSUE THREAD

**Issue by faisal-bhuiyan** [tetonsim/is-cura-ui#611]
_Tested using BCN3D Stratos v4.2.2 + SmartSlice v19.1.9_

When the results come back from a validation job, the results are shaded with the wrong color for the following scenarios:

- FoS requirement is met, while the max displacement requirement is not met. Expected behavior: FoS shaded in something else than red (yellow?).

![wrong_color_fos](https://user-images.githubusercontent.com/59463700/144113750-5b0d2226-45d8-4b7c-b329-fb22ddd86e10.png)

- FoS requirement is not met, while the max displacement is met: returning expected behavior.

![wrong_color_maxdisp](https://user-images.githubusercontent.com/59463700/144120695-61a66133-54f7-48c1-aad7-15563056c168.PNG)

- Both FoS and max displacement requirements are met. Expected behavior: Both entries should have the same color (but not in red).

![wrong_color_fos_maxdisp](https://user-images.githubusercontent.com/59463700/144119876-ac809640-9f07-4fa6-9c85-0bbb2605d6d2.png)

We need to take the state of each requirement (satisfied/unsatisfied) to assign a color to it - seems like the state of FoS is not being considered currently.

**Comment by dougkenik** [comment]
@faisal-bhuiyan - can you provide the model and steps to reproduce?

**Comment by faisal-bhuiyan** [comment]
> @faisal-bhuiyan - can you provide the model and steps to reproduce?

Steps to reproduce: 
- Start with any model 
- Define some anchors + loads on the part (any surface/magnitude should work) -> validate
- Based off the results, tweak the requirements to produce different scenarios of requirements not being satisfied (as discussed in the first comment)

I believe the above should be enough details to reproduce the issue.

**Comment by faisal-bhuiyan** [comment]
Update: I tried to save the model that displays the above behavior - however, I cannot reproduce it. Seems like the issue does not appear on all situations.

Anyhow, I think we should close this ticket.

**Comment by dougkenik** [comment]
Cannot reproduce
