### ISSUE TITLE
Load arrows flip direction after SLT orientation is changed and .3mf is saved and reopened

### ISSUE THREAD

**Issue by Tyler-Heckenlively** [tetonsim/is-cura-ui#616]
Anytime an STL is rotated from its original position the load arrows will not maintain the proper direction after the part has been saved as an .3MF. When the .3mf is saved and reopened the load direction will be flipped from the original selected direction.

Link to video demonstration:
https://tetoncompositescom.sharepoint.com/:v:/r/sites/TetonSimulation/Shared%20Documents/Staff/Interns/Tyler/SmartSlice%20Load%20direction%20flip.mp4?csf=1&web=1&e=1uueo0

**Comment by AijunHall** [comment]
Could be relate to #459

**Comment by Tyler-Heckenlively** [comment]
.3MF for model used in example: https://tetoncompositescom.sharepoint.com/:u:/r/sites/TetonSimulation/Shared%20Documents/R%26D/Models/Switch%20Box/UMS5_Switch%20Box.3mf?csf=1&web=1&e=dIfuh4

**Comment by dougkenik** [comment]
This only occurs when the load arrow is saved in a "flipped" state
