### ISSUE TITLE
Retrieve material usage from pywim from new attribute

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#63]
pywim and wim were incorrectly using a `mass` variable which actually contained the predicted material volume. That has been fixed. The plug-in should update pywim appropriately any change any reference to the `mass` attribute to `material_volume`. Additionally, it was placed into an Extruder class. See the code:

https://github.com/tetonsim/pywim/blob/r20.0/pywim/smartslice/result.py#L11

**Comment by CodyFagley** [comment]
The plugin's side is prepared for this transaction, but I am still using the old teton-pywim.  Let me know if this change is correct, and when to make the swap.

Proposed Change: https://github.com/tetonsim/is-cura-ui/blob/cf-r20-UI-Validation/SmartSlicePlugin/SmartSliceExtension/SmartSliceCloudConnector.py#L400

`Analyse` is a PyWim Analysis Object

**Comment by bradymadams** [comment]
@CodyFagley I'm going to close this issue and move the change requests into #77 . There is more than one change that needs to be made to accommodate the update to the new pywim, so I think it makes sense to do it all at once in one issue.
