### ISSUE TITLE
Error on thin geometry during Validation

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#66]
A relatively thin dogbone geometry errors out during the Smart Slice Validate step. However, the same geometry, only thicker, is successfully validated.

Steps to reproduce:

1. Open the attached geometry file called thin_dogbone.stl in Cura
2. Select Generic ABS as the material
3. Run through the standard Smart Slice workflow. Select the bottom surface as the anchor and the top surface as the loaded surface. (Bottom/top surfaces are in reference to how a dogbone would actually be loaded).
4. Press the Validate button and after about 5 minutes, you should get the following error message:
![error](https://user-images.githubusercontent.com/34459028/72274919-41284900-35ea-11ea-82fc-7d65be166e0a.png)
5. Re-run these steps with the thick_dogbone.stl and note that it is successful. 

[stl_files.zip](https://github.com/tetonsim/is-cura-ui/files/4054660/stl_files.zip)

**Comment by rickdalgarno** [comment]
I tried this with Cura 4.4 and SS build 61 and got a different error:

![image](https://user-images.githubusercontent.com/34459028/75392808-06ccef80-58aa-11ea-8d2d-ac22040b2259.png)

**Comment by rickdalgarno** [comment]
Tested this issue with SmartSlicePlugin-r20.0.81 and it is not longer an issue. I successfully ran a validation with the thin dogbone and the thick dogbone. This is the 1st time I have tried these models with the new voxelizer and region assigner. 

@bradymadams Is this sufficient to close this issue?

**Comment by bradymadams** [comment]
@rickdalgarno yeah I think so. Did the returned FOS and max displacement look reasonable? If so, I'd say let's close it.

**Comment by rickdalgarno** [comment]
FOS and disp. values passed the sniff test. Closing this issues.
