### ISSUE TITLE
Smart Slice plugin affects Cura performance

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#69]
When the Smart Slice plug-in is installed, the behavior of Cura is negatively impacted. 

For example:

1. Open Cura (with Smart Slice plug-in installed) and import the [brake lever stl file](https://tetoncompositescom.sharepoint.com/:u:/s/TetonSimulation/ETDAqT9EMJ1CqC2J_Dt4ZuIBRxo6ltH_d2EScXZ6RlbIZg?e=8UdB86).
2. In the Prepare environment, try to select the part. On Tyler's machine, it stalls then eventually crashes Cura. On Rick's machine, it stalls for several seconds before the Move, Rotate, Scale, ... tools become available.
3. Other known issues are the Marketplace is slow to respond when the Smart-Slice plugin is installed.

In general, we don't want Smart Slice to have any impact on the behavior of Cura, outside of the Smart Slice environment.

**Comment by rickdalgarno** [comment]
@CodyFagley I know we spoke about this bug a few days ago. I am still seeing critical performance issues for certain parts. Specifically, today I installed the latest plugin (build 24) into a clean Cura 4.4.1 install and when I open the attached file and click on the part, Cura stalls for about 1-2 minutes. Not sure if you have actually worked on this or not. This is just another data point.

[Laser Base.zip](https://github.com/tetonsim/is-cura-ui/files/4150866/Laser.Base.zip)

**Comment by CodyFagley** [comment]
Thanks Rick!!  This will be addressed in my next task, but I appreciate having a second model for testing :)

**Comment by rickdalgarno** [comment]
The issues in this ticket appear to have been resolved. The brake pedal and laser base parts do not stall Cura like they used to and the Marketplace is back to "normal" load times. 

Verified with Cura 4.4 and SS build 61
