### ISSUE TITLE
Load Dialogue

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#7]
When a user adds a new load, a user can select a surface. After a surface is selected, a new dialogue will appear centered in the center on the canvas which allows them to edit what the load means, according to the mockups.

If a user selects the arrow icon next to a load, they can reselect a surface, after which the saved load dialogue will appear for that load.

If the user right clicks + edits a load, the preselected surface is highlighted, and the load dialogue appears

The load arrow appears normal to the surface the user selected, pointing to the exterior face of the surface as a default

A few notes:

1) We only allow Push/Pull load type for now
2) User can flip the direction of the arrow through the radio button
3) User can manually enter the magnitude of the load
4) TBD - if a cylindrical surface is selected, the user can drag the arrow around the perimeter of the cylinder to change direction. This cannot happen for a flat surface - it remains constant.

**Comment by CodyFagley** [comment]
NOTE:  Displays correct window/information, but in wrong place.

`TODO:`  Redraw within Scene Node Canvas at selected face.
