### ISSUE TITLE
Extruder Change Warning

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#71]
We currently only support the 1st Extruder in a multi-extruder printer.

If the user changes the Extruder for the geometry to anything but Extruder 1, or the user selects the wall or Infill extruder to Extruder 2, we need to submit a warning to the user (see mockups). The extruder can only be Not Overriden, or Extruder 1

If the user selects Ok, we will change the extruder back to Extruder 1.

Mockups below (Speaker notes have workflow)

https://tetoncompositescom.sharepoint.com/:p:/s/TetonSimulation/ET6obTueAGRKsjXRr4ABqvIBkMhaoeKl7VoYjMN1jBelXg?e=PgtxgZ

**Comment by bradymadams** [comment]
Done in #118
