### ISSUE TITLE
Flip Direction not active when body reselected

### ISSUE THREAD

**Issue by aklempau** [tetonsim/is-cura-ui#78]
See PR #75 for origin of this issue.  Likely already fixed with https://github.com/tetonsim/is-cura-ui/blob/cf-r20-UI-Validation/SmartSlicePlugin/SmartSliceExtension/SmartSlicePropertyHandler.py#L62
Must check after merge of r20.0 with Master.

To reproduce:
Select a face, the arrow appears and Flip Direction works.  Now, mouse click away from the body so the whole body is deactivated.  Then, click the body (anywhere) and the body is active again, but now the face is not active and the Flip Direction does not work.

Important dialogue:
The problem stems from Selection.getSelectedFace() returning None after the body is activated again
In Master branch a change is saving a cache of anchored/loaded faces, whereas in r20 it is not implemented yet.

**Comment by rickdalgarno** [comment]
Confirmed this is fixed in build 63. @bradymadams confirmed he fixed this some time ago.
