### ISSUE TITLE
"SmartSlice was unable to find a solution" message

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#84]
Bug: Improper use of "SmartSlice was unable to find a solution" message

Steps:
1. Open a part in Cura, define a load case and requirements for SS, then click Validate.
2. During validation, change the layer height (or some other influential parameter).
3. Select "Cancel" in the warning message that appears.
4. 2 warning messages appear as shown in the screenshot. The warning message, "SmartSlice was unable to fine a solution" doesn't make sense since the user cancelled the validation. The other message does make sense.

![image](https://user-images.githubusercontent.com/34459028/74293688-c0e42900-4cf8-11ea-9b82-a10f864581b0.png)

_Originally posted by @rickdalgarno in https://github.com/tetonsim/is-cura-ui/pull/81#issuecomment-584959191_

**Comment by bradymadams** [comment]
Let's re-check this after #11 is done.

**Comment by colman-hartinger** [comment]
following the steps to reproduce problem the two error messages that used to show don't anymore but It does switch to the optimize stage when cancel is hit during validation

**Comment by bradymadams** [comment]
Was this done in #171 or do we need to check this?

**Comment by colman-hartinger** [comment]
Ya this was fixed
