### ISSUE TITLE
Changing load magnitude doesn't always change state

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#90]
After a Validation, if the load magnitude is changed, it doesn't always trigger a change from Optimize back to Validate.

SS Build: 60

Scenario that doesn't trigger the change: User changes the load, but doesn't press Enter. The user change swap between the anchor face and load face without triggering a change.

Scenarios that do trigger a change:
1. If the load is changed and the Enter button is pressed
2. If the load is changed and the user clicks Requirements
3. If the load is changed and the user de-selects the body by clicking somewhere else in the UI

These scenarios are shown in the attached video.
[load_change.zip](https://github.com/tetonsim/is-cura-ui/files/4257619/load_change.zip)

**Comment by bradymadams** [comment]
@rickdalgarno is this still an issue?

**Comment by bradymadams** [comment]
Let's re-check this after #55 is done.

**Comment by bradymadams** [comment]
@rickdalgarno can we close this?

**Comment by rickdalgarno** [comment]
Tested this with Beta 3 build and it is fixed. 

Closing this ticket.
