### ISSUE TITLE
Preview stage View type is dependent on import model

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#91]
There are 2 issues to address here:

Issue A. View type in Prepare stage is not consistent. It depends on the .stl file that is loaded in Cura

Steps to reproduce:
1. Open Cura and import the attached pedal fixture. Go to the Preview stage. Note that the "View type" is set to "SmartSlicePlugin". 
2. Repeat the above for the gripper model. Note that the "View type" is now set to "Layer view"
See video for the above workflow. 

Issue B. Why is there a "SmartSlicePlugin" view type? Was there a request to have this feature? I checked with @dougkenik and he said it shouldn't be there. Issue A isn't really the priority here. Issue B is.

[models.zip](https://github.com/tetonsim/is-cura-ui/files/4258215/models.zip)

[View Type.zip](https://github.com/tetonsim/is-cura-ui/files/4258225/View.Type.zip)

Tested config: Cura 4.4 with SS plugin 61

**Comment by CodyFagley** [comment]
I believe that was merged in from r20.0-dev from this commit:
https://github.com/tetonsim/is-cura-ui/commit/d4d596def5dbc431798071a2ff63c5af9cec84ab#diff-4798810e4fed5a18e0e44313e01e0e10R54

**Comment by bradymadams** [comment]
@rickdalgarno I don't think this is a problem anymore. Let me know if you think it is, otherwise, I'll close this.

**Comment by rickdalgarno** [comment]
@bradymadams This is not a problem anymore.
