### ISSUE TITLE
Load direction and moving between stages

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#92]
When the load is defined with the default load direction, users can freely move between stages after a validation without triggering a change in state. When the load is defined with the "Flip Direction" checked, a change in state is triggered if users switch stages after validation.

Steps to reproduce (see videos):
1. Open any model. Run a validate step with the default load direction. After validation, switch to the Prepare and Preview stages, then back to the SS stage. The state is unchanged.
2. Open the same model. Run a validate step with the "Flip Direction" box checked. After validation, switch to Prepare, then back to the SS stage. The state will have reverted back to Validate.

[flip direction.zip](https://github.com/tetonsim/is-cura-ui/files/4258527/flip.direction.zip)

[default direction.zip](https://github.com/tetonsim/is-cura-ui/files/4258525/default.direction.zip)

Config: Cura 4.4 and SS build 61

**Comment by CodyFagley** [comment]
Confirmed this bug.  Resolved with most recent commit:
https://github.com/tetonsim/is-cura-ui/commit/468505a5a69102bf5288a10cb81e5779b40614ec

**Comment by rickdalgarno** [comment]
Confirmed fix with Cura 4.4 and SS build 62.
