### ISSUE TITLE
Mod mesh not shown in SS stage after Optimization

### ISSUE THREAD

**Issue by rickdalgarno** [tetonsim/is-cura-ui#93]
After an Optimization, the modifier mesh is not shown in the SS stage, but it is shown in the other stages. @CodyFagley has noticed this too.

Steps to reproduce (see attached video)

[missing mod mesh.zip](https://github.com/tetonsim/is-cura-ui/files/4264004/missing.mod.mesh.zip)

Test config: Cura 4.4 and SS build 63

**Comment by bradymadams** [comment]
@rickdalgarno please test in latest 20.1 build

**Comment by rickdalgarno** [comment]
Tested using SmartSlicePlugin-r20.1.34. The mod mesh now shows up in the Smart Slice stage after optimization is complete.
