### ISSUE TITLE
Optimized modifier meshes on scaled geometry are double scaled

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#98]
If mod meshes are created in an optimization on a scaled geometry they are getting scaled twice when they're added into the Cura scene.

The shown example is a dogbone scaled 3x in all dimensions.

The screenshot from Paraview shows on the mod meshes were intended to be placed from smartslice. The Cura screenshot shows how they're clearly enlarged, and as a result spaced out.

![mod-meshes-from-smartslice](https://user-images.githubusercontent.com/23110600/76896189-fc719600-6856-11ea-8328-8a9d3c3198d2.png)

![mod-meshes-in-cura](https://user-images.githubusercontent.com/23110600/76896192-fed3f000-6856-11ea-9b6e-3acfbf051e96.png)

**Comment by dougkenik** [comment]
This might be fixed in #125 - @rickdalgarno, can you test?

**Comment by rickdalgarno** [comment]
I will test once there is a new install to test. @bradymadams can you let me know when there is a new build?

**Comment by bradymadams** [comment]
@rickdalgarno https://teton-cdn.s3-us-west-2.amazonaws.com/smartslice-cura-plugin/dist/SmartSlicePlugin-r20.1.3.curapackage

**Comment by rickdalgarno** [comment]
Tested with 20.1.3 on a dogbone. Mod meshes were not scaled in the Cura scene.
